import * as pdfjsLib from "pdfjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/6.3.289/pdf.worker.min.mjs";
const $=s=>document.querySelector(s), app=$("#app"), toastEl=$("#toast");
const state={lang:localStorage.bst_lang||"bn",theme:localStorage.bst_theme||"light",recent:JSON.parse(localStorage.bst_recent||"[]")};
document.documentElement.dataset.theme=state.theme; $("#year").textContent=new Date().getFullYear();
const tools=[
["age-calculator","বয়স ক্যালকুলেটর","জন্মতারিখ থেকে বয়স বের করুন","ক্যালকুলেটর"],["percentage-calculator","Percentage Calculator","শতকরা হিসাব সহজে করুন","ক্যালকুলেটর"],["bmi-calculator","BMI Calculator","উচ্চতা ও ওজন থেকে BMI হিসাব করুন","ক্যালকুলেটর"],["discount-calculator","Discount Calculator","ছাড়ের পর দাম ও সাশ্রয় হিসাব করুন","ক্যালকুলেটর"],["profit-loss-calculator","Profit & Loss","লাভ বা ক্ষতির পরিমাণ ও শতাংশ বের করুন","ফাইন্যান্স"],["salary-calculator","Salary Calculator","মাসিক বেতন থেকে বার্ষিক মোট হিসাব","ফাইন্যান্স"],["vat-calculator","VAT Calculator","VAT যোগ বা বাদ দিয়ে মূল্য হিসাব করুন","ফাইন্যান্স"],["emi-calculator","EMI Calculator","ঋণের মাসিক কিস্তি হিসাব করুন","ফাইন্যান্স"],["date-calculator","Date Calculator","দুই তারিখের ব্যবধান বের করুন","ক্যালকুলেটর"],["currency-converter","Currency Converter","লাইভ exchange rate দিয়ে currency convert করুন","ফাইন্যান্স"],["word-counter","Word Counter","শব্দ ও character গণনা করুন","টেক্সট"],["character-counter","Character Counter","অক্ষর গণনা করুন","টেক্সট"],["case-converter","Case Converter","UPPER, lower ও Title Case করুন","টেক্সট"],["image-compressor","Image Compressor","ছবির file size কমান","ইমেজ"],["image-resizer","Image Resizer","ছবির width ও height পরিবর্তন করুন","ইমেজ"],["jpg-to-png","JPG to PNG","JPG ছবিকে PNG করুন","ইমেজ"],["png-to-jpg","PNG to JPG","PNG ছবিকে JPG করুন","ইমেজ"],["pdf-to-jpg","PDF to JPG","PDF-এর page JPG হিসেবে export করুন","PDF"],["json-formatter","JSON Formatter","JSON format ও validate করুন","ডেভেলপার"],["password-generator","Password Generator","নিরাপদ random password তৈরি করুন","ইউটিলিটি"],["qr-generator","QR Code Generator","Text বা URL থেকে QR code তৈরি করুন","ইউটিলিটি"]];
const blogs=[
["vat-kivabe-hisab","VAT কীভাবে হিসাব করবেন?","VAT-এর basic formula, উদাহরণ ও calculator ব্যবহার।"],["percentage-kivabe","Percentage কীভাবে বের করবেন?","শতকরা বের করার সহজ formula ও বাস্তব উদাহরণ।"],["excel-formula","Excel-এর গুরুত্বপূর্ণ ২০টি Formula","Accounts ও office work-এর জন্য দরকারি Excel formula।"],["tally-journal-entry","Tally Journal Entry কী?","Debit-credit ও journal entry বোঝার সহজ guide।"],["pdf-size-komano","PDF Size কমানোর নিয়ম","Online ও browser-based PDF workflow নিয়ে সহজ guide।"],["website-theke-income","Website থেকে কীভাবে আয় করা যায়?","Ads, affiliate ও useful tools দিয়ে website monetization-এর roadmap।"]];
function toast(t){toastEl.textContent=t;toastEl.classList.add("show");clearTimeout(window.__tt);window.__tt=setTimeout(()=>toastEl.classList.remove("show"),2200)}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast(state.lang==="bn"?"কপি হয়েছে ✓":"Copied ✓")}catch{toast("Copy failed")}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function saveRecent(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);localStorage.bst_recent=JSON.stringify(state.recent)}
function card(t){return `<div class="card tool-card"><div>🛠️</div><h3>${esc(t[1])}</h3><p>${esc(t[2])}</p><a class="btn" href="#/${t[0]}">ব্যবহার করুন →</a></div>`}
function home(){app.innerHTML=`<section class="hero"><div class="container"><h1>বাংলায় সহজ, দ্রুত ও ফ্রি<br>Online Tools</h1><p>Calculator, PDF, Image, Text, Finance ও Developer tools—সব এক জায়গায়।</p><div class="search"><input id="search" class="input" placeholder="যে tool খুঁজছেন লিখুন…"><button class="btn" id="searchBtn">Search</button></div><div class="chips">${[...new Set(tools.map(x=>x[3]))].map(c=>`<a class="chip" href="#/tools?cat=${encodeURIComponent(c)}">${c}</a>`).join("")}</div></div></section><section class="section"><div class="container"><h2>জনপ্রিয় Tools</h2><div class="grid">${tools.slice(0,9).map(card).join("")}</div></div></section><section class="section"><div class="container"><h2>কেন BanglaSmartTools?</h2><div class="grid"><div class="card"><h3>⚡ দ্রুত</h3><p>বেশিরভাগ tool browser-এই কাজ করে।</p></div><div class="card"><h3>🔒 Privacy-friendly</h3><p>যেখানে সম্ভব local browser processing ব্যবহার করা হয়েছে।</p></div><div class="card"><h3>📱 Mobile friendly</h3><p>মোবাইল ও desktop উভয়ের জন্য responsive design।</p></div></div></div></section>`;$("#searchBtn").onclick=()=>searchTools($("#search").value);$("#search").oninput=e=>searchTools(e.target.value)}
function searchTools(q){const a=tools.filter(t=>(t[1]+t[2]+t[3]).toLowerCase().includes(q.toLowerCase()));const box=document.querySelector("#searchResults");if(box)box.innerHTML=a.map(card).join("")||"<p>কোনো tool পাওয়া যায়নি।</p>";else if(q){app.insertAdjacentHTML("beforeend",`<section class="section container" id="searchResults">${a.map(card).join("")||"<p>কোনো tool পাওয়া যায়নি।</p>"}</section>`)}}
function toolsPage(){app.innerHTML=`<section class="section container"><h1>সব Tools</h1><p>আপনার প্রয়োজনীয় free online tool বেছে নিন।</p><div class="grid">${tools.map(card).join("")}</div></section>`}
function blog(){app.innerHTML=`<section class="section container"><h1>Blog</h1><div class="grid">${blogs.map(b=>`<article class="card"><div class="blog-meta">BanglaSmartTools Guide</div><h2>${b[1]}</h2><p>${b[2]}</p><a class="btn" href="#/blog/${b[0]}">পড়ুন →</a></article>`).join("")}</div></section>`}
function article(slug){const b=blogs.find(x=>x[0]===slug)||blogs[0];app.innerHTML=`<article class="article container"><div class="blog-meta">BanglaSmartTools Blog</div><h1>${b[1]}</h1><p>${b[2]}</p><hr><h2>সহজভাবে বুঝুন</h2><p>এই guide-এ আমরা বিষয়টি step-by-step বুঝব। প্রয়োজন অনুযায়ী নিচের BanglaSmartTools calculator বা tool ব্যবহার করে ফলাফল যাচাই করতে পারেন।</p><h2>উদাহরণ</h2><p>প্রথমে প্রয়োজনীয় তথ্য সংগ্রহ করুন, তারপর formula প্রয়োগ করুন এবং শেষে ফলাফল যাচাই করুন। বাস্তব কাজে decimal rounding ও source data অবশ্যই পরীক্ষা করবেন।</p><h2>সারাংশ</h2><p>সময় বাঁচাতে online tool ব্যবহার করুন, তবে গুরুত্বপূর্ণ financial বা legal সিদ্ধান্তের আগে তথ্য যাচাই করুন।</p></article>`}
function form(title,body){app.innerHTML=`<section class="tool-layout"><div class="card"><h1>${title}</h1>${body}</div></section>`}
function result(html){return `<div id="result" class="result">${html}</div>`}
function toolPage(id){saveRecent(id);const t=tools.find(x=>x[0]===id);if(!t)return notFound();const pages={
"age-calculator":()=>{form(t[1],`<div class="field"><label>জন্মতারিখ</label><input id="birth" type="date" class="input"></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল এখানে দেখাবে")}`);$("#go").onclick=()=>{const d=new Date($("#birth").value);if(isNaN(d))return toast("তারিখ দিন");const n=new Date();let y=n.getFullYear()-d.getFullYear(),m=n.getMonth()-d.getMonth(),day=n.getDate()-d.getDate();if(day<0){m--;day+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}$("#result").innerHTML=`আপনার বয়স <b>${y} বছর ${m} মাস ${day} দিন</b>। <div class="actions"><button class="btn alt" onclick="navigator.clipboard.writeText('${y} বছর ${m} মাস ${day} দিন');toast('কপি হয়েছে ✓')">Copy</button></div>`}},
"percentage-calculator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>সংখ্যা</label><input id="a" type="number" class="input"></div><div class="field"><label>শতাংশ (%)</label><input id="b" type="number" class="input"></div></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল")}`);$("#go").onclick=()=>{const v=+$("#a").value*+$("#b").value/100;$("#result").innerHTML=`ফলাফল: <b>${v}</b> <button class="small" id="copy">Copy</button>`;$("#copy").onclick=()=>copyText(String(v))}},
"bmi-calculator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>ওজন (kg)</label><input id="w" type="number" class="input"></div><div class="field"><label>উচ্চতা (cm)</label><input id="h" type="number" class="input"></div></div><button class="btn" id="go">হিসাব করুন</button>${result("BMI ফলাফল")}`);$("#go").onclick=()=>{const v=(+$("#w").value)/Math.pow(+$("#h").value/100,2);$("#result").innerHTML=`BMI: <b>${v.toFixed(2)}</b>`}},
"discount-calculator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>মূল দাম</label><input id="p" type="number" class="input"></div><div class="field"><label>Discount %</label><input id="d" type="number" class="input"></div></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল")}`);$("#go").onclick=()=>{let p=+$("#p").value,d=+$("#d").value,s=p*d/100;$("#result").innerHTML=`Discount: <b>${s.toFixed(2)}</b><br>Final price: <b>${(p-s).toFixed(2)}</b>`}},
"profit-loss-calculator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>ক্রয়মূল্য</label><input id="c" type="number" class="input"></div><div class="field"><label>বিক্রয়মূল্য</label><input id="s" type="number" class="input"></div></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল")}`);$("#go").onclick=()=>{let c=+$("#c").value,s=+$("#s").value,p=s-c,pc=c?p/c*100:0;$("#result").innerHTML=p>=0?`লাভ: <b>${p.toFixed(2)}</b> (${pc.toFixed(2)}%)`:`ক্ষতি: <b>${Math.abs(p).toFixed(2)}</b> (${Math.abs(pc).toFixed(2)}%)`}},
"salary-calculator":()=>{form(t[1],`<div class="field"><label>মাসিক বেতন</label><input id="m" type="number" class="input"></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল")}`);$("#go").onclick=()=>{let m=+$("#m").value;$("#result").innerHTML=`বার্ষিক বেতন: <b>${(m*12).toFixed(2)}</b>`}},
"vat-calculator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>মূল মূল্য</label><input id="p" type="number" class="input"></div><div class="field"><label>VAT %</label><input id="v" type="number" value="15" class="input"></div></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল")}`);$("#go").onclick=()=>{let p=+$("#p").value,v=+$("#v").value,x=p*v/100;$("#result").innerHTML=`VAT: <b>${x.toFixed(2)}</b><br>মোট: <b>${(p+x).toFixed(2)}</b>`}},
"emi-calculator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>Loan amount</label><input id="p" type="number" class="input"></div><div class="field"><label>Annual interest %</label><input id="r" type="number" class="input"></div><div class="field"><label>Months</label><input id="n" type="number" class="input"></div></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল")}`);$("#go").onclick=()=>{let p=+$("#p").value,r=+$("#r").value/1200,n=+$("#n").value,e=r? p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;$("#result").innerHTML=`মাসিক EMI: <b>${e.toFixed(2)}</b>`}},
"date-calculator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>শুরুর তারিখ</label><input id="a" type="date" class="input"></div><div class="field"><label>শেষ তারিখ</label><input id="b" type="date" class="input"></div></div><button class="btn" id="go">হিসাব করুন</button>${result("ফলাফল")}`);$("#go").onclick=()=>{let a=new Date($("#a").value),b=new Date($("#b").value);$("#result").innerHTML=`ব্যবধান: <b>${Math.abs(Math.round((b-a)/86400000))} দিন</b>`}},
"currency-converter":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>Amount</label><input id="amt" type="number" value="1" class="input"></div><div class="field"><label>From</label><select id="from" class="select"><option>BDT</option><option>USD</option><option>EUR</option><option>GBP</option><option>INR</option><option>JPY</option></select></div><div class="field"><label>To</label><select id="to" class="select"><option>USD</option><option>BDT</option><option>EUR</option><option>GBP</option><option>INR</option><option>JPY</option></select></div></div><button class="btn" id="go">Convert</button>${result("Rate loading…")}<p class="blog-meta">Rates are provided by ExchangeRate-API and may update daily.</p>`);$("#go").onclick=async()=>{const amt=+$("#amt").value,from=$("#from").value,to=$("#to").value;try{const r=await fetch(`https://open.er-api.com/v6/latest/${from}`);const j=await r.json();const v=amt*j.rates[to];$("#result").innerHTML=`<b>${amt} ${from} = ${v.toFixed(4)} ${to}</b><br>Rate: 1 ${from} = ${j.rates[to]} ${to}`}catch{toast("Rate পাওয়া যায়নি");$("#result").textContent="Conversion failed"}}},
"word-counter":()=>textCounter(t[1],true),"character-counter":()=>textCounter(t[1],false),
"case-converter":()=>{form(t[1],`<textarea id="txt" class="textarea" placeholder="এখানে লিখুন…"></textarea><div class="actions"><button class="btn" id="upper">UPPER</button><button class="btn" id="lower">lower</button><button class="btn" id="title">Title Case</button><button class="btn alt" id="copy">Copy</button></div>`);const x=$("#txt");$("#upper").onclick=()=>x.value=x.value.toUpperCase();$("#lower").onclick=()=>x.value=x.value.toLowerCase();$("#title").onclick=()=>x.value=x.value.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());$("#copy").onclick=()=>copyText(x.value)},
"json-formatter":()=>{form(t[1],`<textarea id="txt" class="textarea" placeholder='{"name":"Ashik"}'></textarea><div class="actions"><button class="btn" id="format">Format</button><button class="btn alt" id="min">Minify</button><button class="btn alt" id="copy">Copy</button></div>${result("JSON output")}`);const x=$("#txt");$("#format").onclick=()=>{try{$("#result").textContent=JSON.stringify(JSON.parse(x.value),null,2)}catch(e){toast("Invalid JSON")}};$("#min").onclick=()=>{try{$("#result").textContent=JSON.stringify(JSON.parse(x.value))}catch{toast("Invalid JSON")}};$("#copy").onclick=()=>copyText(x.value)},
"password-generator":()=>{form(t[1],`<div class="form-grid"><div class="field"><label>Length</label><input id="n" type="number" min="6" max="128" value="16" class="input"></div></div><button class="btn" id="go">Generate</button>${result("Password")}`);$("#go").onclick=()=>{let n=Math.min(128,Math.max(6,+$("#n").value||16)),chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-";let out="",a=new Uint32Array(n);crypto.getRandomValues(a);for(let i=0;i<n;i++)out+=chars[a[i]%chars.length];$("#result").innerHTML=`<code>${esc(out)}</code> <button class="small" id="copy">Copy</button>`;$("#copy").onclick=()=>copyText(out)}},
"qr-generator":()=>{form(t[1],`<input id="txt" class="input" placeholder="Text বা URL"><button class="btn" id="go">Generate QR</button><div id="qr" class="result"></div>`);$("#go").onclick=()=>{$("#qr").innerHTML="";new QRCode($("#qr"),{text:$("#txt").value,width:220,height:220})}},
"image-compressor":()=>imageTool(t[1],"compress"),"image-resizer":()=>imageTool(t[1],"resize"),"jpg-to-png":()=>imageTool(t[1],"jpgpng"),"png-to-jpg":()=>imageTool(t[1],"pngjpg"),
"pdf-to-jpg":()=>pdfTool(t[1])};(pages[id]||generic)(t[1])}
function textCounter(title,words){form(title,`<textarea id="txt" class="textarea"></textarea>${result("0")}`);$("#txt").oninput=e=>{let s=e.target.value;$("#result").textContent=words?`Words: ${s.trim()?s.trim().split(/\s+/).length:0} | Characters: ${s.length}`:`Characters: ${s.length}`}}
function imageTool(title,type){form(title,`<div class="drop"><input id="file" type="file" accept="image/*"></div><div id="opts"></div>${result("Image result")}`);$("#file").onchange=async e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>{let w=im.width,h=im.height;if(type==="resize"){w=+prompt("Width",w)||w;h=+prompt("Height",h)||h}const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d");if(type==="pngjpg") {ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h)}ctx.drawImage(im,0,0,w,h);const mime=type==="jpgpng"?"image/png":type==="pngjpg"?"image/jpeg":"image/jpeg";c.toBlob(b=>{const url=URL.createObjectURL(b);$("#result").innerHTML=`<a class="btn" href="${url}" download="banglasmarttools.${mime.split('/')[1]}">Download</a><br><small>${Math.round(b.size/1024)} KB</small>`},mime,type==="compress"?.75:0.92)};im.src=URL.createObjectURL(f)}}
async function pdfTool(title){form(title,`<div class="drop"><input id="file" type="file" accept="application/pdf"></div>${result("PDF page previews will appear here")}`);$("#file").onchange=async e=>{const f=e.target.files[0];if(!f)return;const data=new Uint8Array(await f.arrayBuffer());const pdf=await pdfjsLib.getDocument({data}).promise;let html=`<b>${pdf.numPages} pages found</b><div class="grid" style="margin-top:15px">`;for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),vp=page.getViewport({scale:1.4}),c=document.createElement("canvas");c.width=vp.width;c.height=vp.height;await page.render({canvasContext:c.getContext("2d"),viewport:vp}).promise;const blob=await new Promise(r=>c.toBlob(r,"image/jpeg",.9)),url=URL.createObjectURL(blob);html+=`<div class="card"><img style="max-width:100%" src="${url}"><br><a class="btn" href="${url}" download="page-${i}.jpg">Download page ${i}</a></div>`}html+=`</div>`;$("#result").innerHTML=html}}
function generic(title){form(title,`<p>এই tool-এর জন্য interface প্রস্তুত করা হয়েছে।</p><div class="actions"><button class="btn" onclick="toast('Coming soon')">Start</button></div>`)}
function legal(type){const data={about:["About Us","BanglaSmartTools একটি বাংলা-কেন্দ্রিক free online tools platform। আমাদের লক্ষ্য হলো everyday calculation, text, image, PDF এবং utility কাজ সহজ করা।"],contact:["Contact","Email: ashikmondol10@gmail.com<br>Phone/WhatsApp: +880 1629272027"],privacy:["Privacy Policy","আমরা প্রয়োজন ছাড়া ব্যক্তিগত তথ্য সংগ্রহ করি না। Browser-based tools-এর input সাধারণত আপনার device-এই process হয়। Third-party services যেমন currency API ব্যবহার করলে তাদের নিজস্ব terms ও privacy policy প্রযোজ্য হতে পারে। আমরা security-এর জন্য reasonable measures অনুসরণ করি, তবে internet transmission-এর সম্পূর্ণ নিরাপত্তা guarantee করা যায় না।"],terms:["Terms & Conditions","এই website-এর tools সাধারণ informational এবং convenience purpose-এর জন্য। ফলাফলের accuracy আপনার input-এর উপর নির্ভর করে। Financial, legal বা medical decision নেওয়ার আগে qualified professional-এর পরামর্শ নিন। Website-এর content ও tools পরিবর্তন, update বা বন্ধ করার অধিকার সংরক্ষিত।"],disclaimer:["Disclaimer","BanglaSmartTools কোনো financial, legal, medical বা professional advice প্রদান করে না। Online calculation-কে final authority হিসেবে ব্যবহার করবেন না। External links/services-এর availability বা accuracy-এর জন্য আমরা দায়ী নই।"]};const d=data[type]||data.about;app.innerHTML=`<section class="legal container"><h1>${d[0]}</h1><p>${d[1]}</p><h2>সাধারণ তথ্য</h2><p>এই policy/page প্রয়োজন অনুযায়ী update হতে পারে। গুরুত্বপূর্ণ পরিবর্তন হলে website-এ নতুন version প্রকাশ করা হবে।</p></section>`}
function notFound(){app.innerHTML=`<section class="legal container"><h1>Page not found</h1><p>দুঃখিত, পেজটি পাওয়া যায়নি।</p><a class="btn" href="#/">হোমে ফিরুন</a></section>`}
function route(){let r=location.hash.slice(2)||"";if(r==="")return home();if(r.startsWith("blog/"))return article(r.slice(5));if(["about","contact","privacy","terms","disclaimer"].includes(r))return legal(r);if(r==="tools")return toolsPage();if(r.startsWith("search"))return home();return toolPage(r)}
$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");$("#themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=state.theme;localStorage.bst_theme=state.theme};$("#langBtn").onclick=()=>{state.lang=state.lang==="bn"?"en":"bn";localStorage.bst_lang=state.lang;$("#langBtn").textContent=state.lang==="bn"?"EN":"BN";toast(state.lang==="bn"?"বাংলা ভাষা সক্রিয়":"English mode active")};window.addEventListener("hashchange",route);window.toast=toast;route();
